# Generated by Django 3.2.14 on 2022-07-08 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codCliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nomeCliente', models.CharField(max_length=100)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=100)),
                ('classeSocial', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codProduto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(max_length=10)),
                ('estoqueMinimo', models.IntegerField()),
                ('qtdEstoque', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('codVenda', models.AutoField(primary_key=True, serialize=False)),
                ('dataVenda', models.DateField(auto_now=True)),
                ('codCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdProduto', models.IntegerField()),
                ('codProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.produto')),
                ('codVenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.venda')),
            ],
        ),
    ]
