# Generated by Django 4.0.6 on 2022-08-02 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codCliente', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nomeCliente', models.CharField(max_length=100)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classeSocial', models.CharField(max_length=1)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codProduto', models.AutoField(primary_key=True, serialize=False, verbose_name='Código do Produto')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('estoqueMinimo', models.IntegerField(verbose_name='Estoque Minimo')),
                ('qtdEstoque', models.IntegerField(verbose_name='Quantidade em estoque')),
                ('imgProduto', models.ImageField(upload_to='produtos/', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('codVenda', models.AutoField(primary_key=True, serialize=False)),
                ('dataVenda', models.DateField(auto_now=True)),
                ('codCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdProduto', models.IntegerField()),
                ('codProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.produto')),
                ('codVenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.venda')),
            ],
        ),
    ]
