# Generated by Django 3.2.14 on 2022-07-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='classeSocial',
            field=models.CharField(max_length=1),
        ),
    ]
