# Generated by Django 3.2.14 on 2022-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='infProduto',
            field=models.TextField(blank=True, verbose_name='Informações do Produto'),
        ),
    ]
