# Generated by Django 3.2.14 on 2022-07-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_cliente_classesocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codCliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
