# Generated by Django 3.2.14 on 2022-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_cliente_codcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imgProduto',
            field=models.ImageField(blank=True, upload_to='produtos/'),
        ),
    ]
