# Generated by Django 4.1 on 2022-08-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_codvenda_detalhevenda_coddetalhevenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('codCliente', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nomeCliente', models.CharField(max_length=100)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('classeSocial', models.CharField(max_length=1)),
            ],
        ),
    ]
